# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e08b151c747707a0273b494a73a882ce85367d8df463c219cbed12133764e4f472409c730cd16829c327770c08bd04108e596f0575f6d900b7195cd3f025ca47

test:
  secret_key_base: 5ae95623df71a4e4599decd95a52f86ee8b0257ccc5b1ce9cbec7b964fe3803ee89ecc9196551b3aaaeb5657a33256d783afca622584b531a52c328918d1b8d0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
